/**
 * Swahili, keyed by the English it replaces.
 *
 * Written for Tanzanian usage rather than textbook Swahili: "hisa" for shares,
 * "salio" for balance, "weka pesa" for a deposit, because that is what a
 * customer reading this already says. Financial and legal wording is the part
 * most worth a native reviewer's eye before this carries real volume.
 *
 * A missing entry falls through to English on purpose. Half a sentence in each
 * language is worse than a whole one in the wrong language.
 */
export const SW: Record<string, string> = {
  // --- navigation ---
  "Markets": "Masoko",
  "Portfolio": "Uwekezaji",
  "How it works": "Jinsi inavyofanya kazi",
  "Open account": "Fungua akaunti",
  "Open an account": "Fungua akaunti",
  "Sign in": "Ingia",
  "Sign out": "Toka",
  "Home": "Mwanzo",
  "Account": "Akaunti",
  "Settings": "Mipangilio",
  "All markets": "Masoko yote",

  // --- hero and landing ---
  "Own the open": "Miliki soko",
  "market.": "Dunia.",
  "US shares in dollars. Tanzanian shares in shillings. Settled against custody published on Base.":
    "Hisa za Marekani kwa dola. Hisa za Tanzania kwa shilingi. Hulipwa dhidi ya dhamana iliyochapishwa kwenye Base.",
  "Explore markets": "Tazama masoko",
  "Onchain value": "Thamani ya mnyororo",
  "Dar es Salaam": "Dar es Salaam",
  "buy in shillings": "nunua kwa shilingi",

  // --- the ticket ---
  "You pay": "Unalipa",
  "Buy": "Nunua",
  "Sell": "Uza",
  "You receive": "Unapokea",
  "Shares": "Hisa",
  "Shares sold": "Hisa zilizouzwa",
  "Price": "Bei",
  "Total cost": "Gharama jumla",
  "You receive ": "Unapokea ",
  "Spend (TZS)": "Tumia (TZS)",
  "Shares to sell": "Hisa za kuuza",
  "Receive about (TZS)": "Utapokea takriban (TZS)",
  "By amount": "Kwa kiasi",
  "By shares": "Kwa hisa",
  "All": "Zote",
  "Buy CRDB": "Nunua CRDB",
  "Sell CRDB": "Uza CRDB",
  "Placing…": "Inatuma…",
  "Indicative. Real quote on the": "Ni makadirio. Bei halisi iko kwenye",
  "asset page": "ukurasa wa hisa",
  "TZS a share": "TZS kwa hisa",
  "Dar es Salaam Stock Exchange": "Soko la Hisa la Dar es Salaam",
  "DSE live": "DSE moja kwa moja",
  "DSE close": "Bei ya kufunga DSE",
  "Proof of reserves": "Uthibitisho wa akiba",
  "Add money": "Weka pesa",
  "Buy shares": "Nunua hisa",
  "Sell shares": "Uza hisa",
  "Withdraw": "Toa pesa",

  // --- portfolio and wallet ---
  "Your book.": "Mali zako.",
  "Cash": "Pesa",
  "Total value": "Thamani jumla",
  "Return": "Faida",
  "held by CAPX": "inashikiliwa na CAPX",
  "Available to invest": "Pesa za kuwekeza",
  "each spent in its own currency": "kila moja hutumika kwa sarafu yake",
  "in shares": "katika hisa",
  "Bought": "Umenunua",
  "Sold": "Umeuza",
  "Activity": "Shughuli",
  "Clear": "Futa",
  "Nothing yet. Add money to get started.": "Bado hakuna kitu. Weka pesa ili kuanza.",
  "after your first buy": "baada ya ununuzi wako wa kwanza",
  "Wallet": "Mkoba",
  "How you are paying": "Unalipaje",
  "Amount": "Kiasi",
  "Amount in shillings": "Kiasi kwa shilingi",
  "Amount to withdraw": "Kiasi cha kutoa",
  "Send to mobile money": "Tuma kwenye simu ya pesa",
  "Sending to": "Inatumwa kwa",
  "They receive": "Watapokea",
  "Bank account you are sending from": "Akaunti ya benki unayotumia kutuma",
  "You have no shares to sell yet": "Bado huna hisa za kuuza",
  "Deposit": "Amana",
  "Proceeds": "Mapato",
  "Paid": "Imelipwa",
  "invested": "zimewekezwa",

  // --- verification ---
  "Verification": "Uthibitishaji",
  "Verify your identity to keep using your account.":
    "Thibitisha utambulisho wako ili uendelee kutumia akaunti yako.",
  "Verify now": "Thibitisha sasa",
  "Try again": "Jaribu tena",
  "Your verification is being reviewed. Nothing to do.":
    "Uthibitishaji wako unakaguliwa. Hakuna la kufanya.",
  "Verification was not accepted. Please submit again.":
    "Uthibitishaji haukukubaliwa. Tafadhali wasilisha tena.",
  "Confirm it’s you.": "Thibitisha ni wewe.",
  "Two photographs: the document you hold, and you holding the phone. It takes about a minute and only has to be done once.":
    "Picha mbili: hati uliyo nayo, na wewe ukiwa umeshika simu. Inachukua takriban dakika moja na hufanyika mara moja tu.",
  "Your document.": "Hati yako.",
  "Your document": "Hati yako",
  "A photo of you, now": "Picha yako, sasa hivi",
  "A photo of you, now.": "Picha yako, sasa hivi.",
  "National ID (NIDA)": "Kitambulisho cha Taifa (NIDA)",
  "Passport": "Paspoti",
  "Driver's licence": "Leseni ya udereva",
  "Voter's card": "Kadi ya mpiga kura",
  "Document number (optional)": "Namba ya hati (si lazima)",
  "Photograph or upload your document (JPEG, PNG or PDF)":
    "Piga picha au pakia hati yako (JPEG, PNG au PDF)",
  "That file is too large. The limit is 6MB.": "Faili hilo ni kubwa mno. Kikomo ni MB 6.",
  "That file could not be read. Try a JPEG, PNG or PDF.":
    "Faili hilo halikusomeka. Jaribu JPEG, PNG au PDF.",
  "Document attached.": "Hati imeambatishwa.",
  "Replace": "Badilisha",
  "Photo taken.": "Picha imepigwa.",
  "Retake": "Piga tena",
  "Open camera": "Fungua kamera",
  "Take photo": "Piga picha",
  "Cancel": "Ghairi",
  "Taken here rather than uploaded, so it matches the document.":
    "Inapigwa hapa badala ya kupakiwa, ili ilingane na hati.",
  "Camera access was refused. Allow it in your browser settings and try again.":
    "Ruhusa ya kamera ilikataliwa. Iruhusu kwenye mipangilio ya kivinjari kisha ujaribu tena.",
  "Submit for verification": "Wasilisha kwa uthibitishaji",
  "Submitting…": "Inawasilisha…",
  "Submitted": "Imewasilishwa",
  "Thanks. We’ll take a look.": "Asante. Tutaiangalia.",
  "Verified": "Imethibitishwa",
  "Under review": "Inakaguliwa",
  "Not accepted": "Haikukubaliwa",
  "Not started": "Haijaanza",
  "Verify your account": "Thibitisha akaunti yako",
  "Verify your identity": "Thibitisha utambulisho wako",
  "Your identity has been confirmed. Nothing more to do here.":
    "Utambulisho wako umethibitishwa. Hakuna zaidi la kufanya hapa.",
  "Your verification is being reviewed. You can keep going below while we look at it.":
    "Uthibitishaji wako unakaguliwa. Unaweza kuendelea hapa chini wakati tunauangalia.",
  "Open your account first, then we will confirm who you are.":
    "Fungua akaunti yako kwanza, kisha tutathibitisha wewe ni nani.",
  "Identity document": "Hati ya utambulisho",
  "National ID": "Kitambulisho cha Taifa",
  "NIDA number": "Namba ya NIDA",
  "Passport number": "Namba ya paspoti",
  "Licence number": "Namba ya leseni",
  "Voter number": "Namba ya mpiga kura",
  "Submit again": "Wasilisha tena",
  "View status": "Angalia hali",

  // --- settings ---
  "Your account.": "Akaunti yako.",
  "Display name": "Jina la kuonyesha",
  "Mobile money number": "Namba ya simu ya pesa",
  "Used for deposits and withdrawals.": "Hutumika kwa amana na kutoa pesa.",
  "Save changes": "Hifadhi mabadiliko",
  "Saving…": "Inahifadhi…",
  "Email": "Barua pepe",
  "Country": "Nchi",
  "Twenty digits. Must match the document you submit for verification.":
    "Tarakimu ishirini. Lazima ilingane na hati utakayowasilisha kwa uthibitishaji.",
  "Verified and locked to the document we checked.":
    "Imethibitishwa na imefungwa kwenye hati tuliyokagua.",
  "Language": "Lugha",
  "Tap feedback": "Mrejesho wa kugusa",
  "Click on": "Mlio umewashwa",
  "Click off": "Mlio umezimwa",
  "This iPhone is older than iOS 18, the first version a website can use the Taptic Engine. A short click can be played instead. It is sound, not vibration.":
    "iPhone hii ni ya zamani kuliko iOS 18, ambayo ndiyo toleo la kwanza tovuti inaweza kutumia Taptic Engine. Badala yake mlio mfupi unaweza kupigwa. Ni sauti, si mtetemo.",
  "Legal": "Kisheria",
  "These terms describe how CAPX actually operates today. They have not yet been reviewed by a licensed Tanzanian advocate, and will be updated when they are. If anything here conflicts with Tanzanian law, the law applies.":
    "Masharti haya yanaeleza jinsi CAPX inavyofanya kazi leo. Bado hayajakaguliwa na wakili aliyesajiliwa Tanzania, na yatasasishwa yatakapokaguliwa. Kama kitu chochote hapa kinapingana na sheria za Tanzania, sheria ndiyo inayotumika.",
  "Terms of service": "Masharti ya huduma",
  "Privacy policy": "Sera ya faragha",

  // --- money and errors ---
  "Your balance is": "Salio lako ni",
  "You need": "Unahitaji",
  "more.": "zaidi.",
  "Could not reach the server. Nothing was placed.":
    "Imeshindwa kufikia seva. Hakuna agizo lililotumwa.",
  "Could not reach the server.": "Imeshindwa kufikia seva.",
  "Loading…": "Inapakia…",
  // --- how it works ---
  // Technical nouns stay in English where that is how they are actually said:
  // Chainlink, B20, multiplier, oracle. Borrowing them is natural Swahili here,
  // and inventing translations would make the page harder to read, not easier.
  "No black box.": "Hakuna siri.",
  "Just addresses.": "Ni anwani tu.",
  "CAPX is a thin, honest interface over machinery that already exists on Base. Here is exactly what it reads, and where you can check it yourself.":
    "CAPX ni kiolesura chepesi na cha kweli juu ya mfumo ambao tayari upo kwenye Base. Haya ndiyo hasa inayosoma, na mahali unapoweza kuthibitisha mwenyewe.",
  "Contracts CAPX reads": "Mikataba ambayo CAPX inasoma",
  "Straight answers": "Majibu ya moja kwa moja",
  "Base documentation": "Nyaraka za Base",
  "Every B20 address begins 0xb2. They are native precompiles on Base, not deployed bytecode.":
    "Kila anwani ya B20 huanza na 0xb2. Ni precompiles za asili kwenye Base, si bytecode iliyosambazwa.",

  "The issuer mints a B20 token": "Mtoaji hutengeneza tokeni ya B20",
  "A regulated issuer holds the underlying share and mints a matching B20 token on Base. B20 extends ERC-20 for real-world assets and is asset-agnostic. These tokens are native precompiles rather than separately deployed contracts, audited by Base and Spearbit with ongoing Cantina and HackerOne bounty coverage.":
    "Mtoaji aliyesajiliwa hushika hisa halisi na kutengeneza tokeni ya B20 inayolingana kwenye Base. B20 huongeza ERC-20 kwa ajili ya mali halisi na haijafungwa kwa aina moja ya mali. Tokeni hizi ni precompiles za asili badala ya mikataba iliyosambazwa peke yake, zilizokaguliwa na Base na Spearbit, na zina ulinzi endelevu wa zawadi kupitia Cantina na HackerOne.",

  "Chainlink publishes a total-return mark": "Chainlink huchapisha bei ya total-return",
  "Each asset has a Chainlink feed on Base reporting price × multiplier, WAD-scaled, running 24/5 and freezing through corporate actions. CAPX reads updatedAt on every round and flags a feed that has missed a session instead of showing you a confident number that isn't.":
    "Kila mali ina Chainlink feed kwenye Base inayoripoti bei × multiplier, kwa kipimo cha WAD, ikifanya kazi saa 24 kwa siku 5 na kusimama wakati wa maamuzi ya kampuni. CAPX husoma updatedAt kwa kila raundi na huonyesha alama pale feed imekosa kipindi, badala ya kukuonyesha namba inayoonekana ya uhakika kumbe si kweli.",

  "Corporate actions move the multiplier": "Maamuzi ya kampuni hubadilisha multiplier",
  "Splits and dividends do not rewrite balances. They adjust a WAD-precision multiplier, so one token is not permanently one share. CAPX applies the current multiplier everywhere a share count appears: portfolio quantities use scaledBalanceOf, and supply figures are multiplier-adjusted share-equivalents.":
    "Kugawanya hisa na gawio havibadilishi salio lako. Hurekebisha multiplier ya usahihi wa WAD, hivyo tokeni moja si hisa moja milele. CAPX hutumia multiplier ya sasa kila mahali idadi ya hisa inapoonekana: idadi za uwekezaji hutumia scaledBalanceOf, na takwimu za ugavi ni sawa na hisa baada ya kurekebishwa kwa multiplier.",

  "Policies gate transfers, not holding": "Sera hudhibiti uhamishaji, si umiliki",
  "Onchain policy registries enforce allowlists and blocklists, and a transfer to a sanctioned address reverts. Holding and secondary transfer are otherwise permissionless. KYC applies at mint and redeem with the issuer, not between wallets.":
    "Rejista za sera kwenye mnyororo hutekeleza orodha za kuruhusu na kuzuia, na uhamishaji kwenda anwani iliyozuiwa hukataliwa. Vinginevyo, kushika na kuhamisha hisa hakuhitaji ruhusa. KYC hutumika wakati wa kutengeneza na kukomboa na mtoaji, si kati ya pochi na pochi.",

  "CAPX reads, you sign": "CAPX husoma, wewe unasaini",
  "Prices, supply and balances are read straight from Base. Trades are routed by aggregating every venue on the chain: Aerodrome concentrated liquidity, Uniswap v3 and v4, PancakeSwap, because equity liquidity moves between them and no single pool tells the truth. Every fill is checked against the Chainlink mark before it is offered, and CAPX refuses to route anything more than 15% away from it.":
    "Bei, ugavi na salio husomwa moja kwa moja kutoka Base. Biashara hupitishwa kwa kukusanya kila soko kwenye mnyororo: Aerodrome concentrated liquidity, Uniswap v3 na v4, PancakeSwap, kwa sababu ukwasi wa hisa husogea kati yao na hakuna dimbwi moja linalosema ukweli wote. Kila biashara hukaguliwa dhidi ya bei ya Chainlink kabla ya kutolewa, na CAPX hukataa kupitisha lolote lililo zaidi ya asilimia 15 kutoka kwake.",

  "Is one token one share?": "Je, tokeni moja ni hisa moja?",
  "No. Redemption applies the current onchain multiplier, which absorbs splits and dividends. CAPX shows the multiplier on every asset page and adjusts every share count it displays.":
    "Hapana. Ukombozi hutumia multiplier ya sasa kwenye mnyororo, ambayo huchukua kugawanya hisa na gawio. CAPX huonyesha multiplier kwenye kila ukurasa wa hisa na hurekebisha kila idadi ya hisa inayoonyesha.",

  "Why does an asset show zero onchain supply?": "Kwa nini hisa fulani inaonyesha ugavi sifuri kwenye mnyororo?",
  "The Chainlink feed is live for all thirteen assets, but tokens are only minted as demand arrives. A supply of zero means nothing has been minted on Base yet. The mark is still real, there is just nothing to trade against.":
    "Chainlink feed inafanya kazi kwa hisa zote kumi na tatu, lakini tokeni hutengenezwa pale mahitaji yanapofika. Ugavi wa sifuri maana yake hakuna kilichotengenezwa kwenye Base bado. Bei bado ni halisi, ila hakuna cha kufanyia biashara.",

  "Why can't I trade every asset?": "Kwa nini siwezi kufanya biashara ya kila hisa?",
  "Secondary trading needs minted supply and a venue holding it. Four assets route today at roughly the oracle mark; the rest have nothing minted on Base yet, so CAPX marks them mint-only rather than inventing a fill. The markets table labels each one.":
    "Biashara ya pili inahitaji ugavi uliotengenezwa na soko linaloushika. Hisa nne zinapitishwa leo karibu na bei ya oracle; zilizobaki hazina kilichotengenezwa kwenye Base bado, hivyo CAPX huziweka alama ya kutengeneza tu badala ya kubuni biashara. Jedwali la masoko huweka alama kwa kila moja.",

  "Who can use this?": "Nani anaweza kutumia hii?",
  "Tokenized equities are not available to US persons. Connect your own wallet and CAPX holds nothing. Fund an account with Tanzanian shillings and CAPX holds those assets for you, recording your entitlement in its own ledger. That is custody, and it is the trade-off for not needing a wallet. Nothing here is investment advice.":
    "Hisa za kidijitali hazipatikani kwa watu wa Marekani. Unganisha pochi yako mwenyewe na CAPX haishiki chochote. Weka pesa kwa shilingi za Tanzania na CAPX hushika mali hizo kwa niaba yako, ikirekodi haki yako kwenye daftari lake. Hiyo ni udhamini, na ndiyo bei ya kutohitaji pochi. Hakuna chochote hapa ni ushauri wa uwekezaji.",

  "oracle-implied": "kwa makadirio ya oracle",
  "Review": "Kagua",
  "order": "agizo",
  "Search company or ticker": "Tafuta kampuni au alama",
  "Shillings": "Shilingi",
  "Tradeable": "Inanunulika",
  "No company matches": "Hakuna kampuni inayolingana",

  // --- remaining interface ---
  "A message from CAPX": "Ujumbe kutoka CAPX",
  "Amount (TZS)": "Kiasi (TZS)",
  "Approve the prompt on your phone. No card, no bank transfer.": "Kubali ujumbe kwenye simu yako. Hakuna kadi, hakuna uhamisho wa benki.",
  "Assets": "Mali",
  "Available": "Zinapatikana",
  "Available to buy": "Zinazopatikana kununua",
  "B20 precision": "Usahihi wa B20",
  "Biggest drawdowns": "Zilizoshuka zaidi",
  "Buy Tanzanian shares in shillings, settled in nTZS": "Nunua hisa za Tanzania kwa shilingi, hulipwa kwa nTZS",
  "By sector": "Kwa sekta",
  "CAPX Equities": "CAPX Equities",
  "CAPX Feeds": "CAPX Feeds",
  "Live prices from Chainlink, updated around the clock. Every price you see comes directly from the blockchain.": "Bei za moja kwa moja kutoka Chainlink, zinazosasishwa saa zote. Kila bei unayoiona inatoka moja kwa moja kwenye mnyororo.",
  // The brand tagline, kept as it is said rather than translated literally.
  "Capital In Motion": "Capital In Motion",
  "Your assets, your wallet. We give you access to global capital markets.": "Mali zako, mkoba wako. Tunakupa fursa ya kuingia kwenye masoko ya mitaji duniani.",
  "CAPX places the trade onchain and records your holding.": "CAPX hufanya biashara kwenye mnyororo na kurekodi umiliki wako.",
  "CAPX will not route this trade. Use issuer mint and redeem instead.": "CAPX haitapitisha biashara hii. Tumia kutengeneza na kukomboa kwa mtoaji badala yake.",
  "Cost basis": "Gharama ya ununuzi",
  "Could not rebuild your cost basis": "Imeshindwa kuhesabu upya gharama yako ya ununuzi",
  "Custodial trading is not enabled on this deployment yet.": "Biashara ya udhamini bado haijawashwa kwenye mfumo huu.",
  "Disconnect": "Tenganisha",
  "Discover CAPX Equities": "Gundua CAPX Equities",
  "Enter an amount": "Weka kiasi",
  "Every claim on this page resolves to an onchain address you can check yourself.": "Kila dai kwenye ukurasa huu linaishia kwenye anwani ya mnyororo unayoweza kuthibitisha mwenyewe.",
  "Each tokenised security here is backed one-for-one by shares held with a licensed custodian. This page shows what is held, what has been issued against it, and when custody was last confirmed. It updates on its own and needs no account.":
    "Kila dhamana iliyowekwa kwenye tokeni hapa inaungwa mkono moja kwa moja na hisa zinazoshikiliwa na mtunzaji mwenye leseni. Ukurasa huu unaonyesha kinachoshikiliwa, kilichotolewa dhidi yake, na mara ya mwisho umiliki ulipothibitishwa. Hujisasisha wenyewe na hauhitaji akaunti.",
  "Custodian": "Mtunzaji",
  "Not yet attested": "Bado haijathibitishwa",
  "Last verified": "Ilithibitishwa mwisho",
  "Attestation expires": "Uthibitisho unaisha",
  "Expired. Issuance is halted": "Umeisha. Utoaji umesimamishwa",
  "Token": "Tokeni",
  "Not deployed": "Haijatumwa",
  "Every share, accounted for.": "Kila hisa, imehesabiwa.",
  "Everything, marked to the chain.": "Kila kitu, kimepimwa kwa mnyororo.",
  "Export CSV": "Pakua CSV",
  "Feed status": "Hali ya feed",
  "Fund with mobile money": "Weka pesa kwa simu",
  "Fund with shillings": "Weka pesa kwa shilingi",
  "Held by customers": "Zinazoshikiliwa na wateja",
  "How a deposit works": "Jinsi amana inavyofanya kazi",
  "Institutional grade": "Kiwango cha kitaasisi",
  "Latest round": "Raundi ya mwisho",
  "Live board": "Ubao wa moja kwa moja",
  "Live feeds": "Feeds za moja kwa moja",
  "Locked in custody": "Zilizofungwa kwenye dhamana",
  "Market value": "Thamani ya soko",
  "Mint only": "Kutengeneza tu",
  "More than you hold": "Zaidi ya ulizonazo",
  "Multiplier": "Multiplier",
  "No B20 positions yet": "Bado huna hisa za B20",
  "No price history available from the exchange right now.": "Hakuna historia ya bei kutoka sokoni kwa sasa.",
  "No secondary market yet": "Bado hakuna soko la pili",
  "No securities have been issued yet.": "Bado hakuna hisa zilizotolewa.",
  "Not available to US persons": "Haipatikani kwa watu wa Marekani",
  "Nothing yet. Deposits and trades show up here.": "Bado hakuna kitu. Amana na biashara zitaonekana hapa.",
  "Onchain references": "Marejeo ya mnyororo",
  "Onchain supply": "Ugavi kwenye mnyororo",
  "Open portfolio": "Fungua uwekezaji",
  "Oracle rounds read": "Raundi za oracle zilizosomwa",
  "Order ticket": "Fomu ya agizo",
  "Read your positions off Base.": "Soma hisa zako moja kwa moja kutoka Base.",
  "Scroll to explore": "Sogeza chini kuona zaidi",
  "Search ticker, company or sector": "Tafuta alama, kampuni au sekta",
  "Session P&L": "Faida ya kipindi hiki",
  "Shares held": "Hisa ulizonazo",
  "Sign in first.": "Ingia kwanza.",
  "Sign in to CAPX": "Ingia CAPX",
  "Signed in": "Umeingia",
  "Snapshot": "Picha ya sasa",
  "Switch to Base to trade": "Badilisha kwenda Base ili kufanya biashara",
  "They convert automatically.": "Hubadilishwa kiotomatiki.",
  "Token decimals": "Desimali za tokeni",
  "Tokenized equities are not available to US persons. Nothing here is investment advice.": "Hisa za kidijitali hazipatikani kwa watu wa Marekani. Hakuna chochote hapa ni ushauri wa uwekezaji.",
  "Tokens outstanding": "Tokeni zilizopo",
  "Top movers": "Zilizopanda zaidi",
  "Transparency": "Uwazi",
  "USDC, ready to deploy.": "USDC, tayari kuwekeza.",
  "Underlying shares": "Hisa halisi",
  "Unrealised": "Ambazo hazijauzwa",
  "Usually within a minute, ready to invest.": "Kwa kawaida ndani ya dakika moja, tayari kuwekeza.",
  "Welcome to CAPX": "Karibu CAPX",
  "What that means": "Maana yake",
  "What you actually paid.": "Ulicholipa hasa.",
  "You buy shares.": "Unanunua hisa.",
  "You receive (est.)": "Utapokea (makadirio)",
  "Your details live behind your account.": "Taarifa zako ziko nyuma ya akaunti yako.",
  "Your name": "Jina lako",
  "Your onchain book.": "Mali zako kwenye mnyororo.",
  // A registered company name. Listed so the coverage check stays honest about
  // what is deliberately untranslated rather than what was forgotten.
  "CRDB Bank Plc": "CRDB Bank Plc",
  "Tanzania’s largest bank by assets. One CRDBt is one share, held in custody for you.":
    "Benki kubwa zaidi Tanzania kwa mali. CRDBt moja ni hisa moja, inayoshikiliwa kwa niaba yako.",
  "And beyond the DSE": "Na zaidi ya DSE",
  "Browse US equities": "Tazama hisa za Marekani",
  "Buy CRDB in shillings": "Nunua CRDB kwa shilingi",
  "Buy a fraction of a DSE-listed company from mobile money. No broker visit, no minimum lot, no waiting three days to settle.": "Nunua sehemu ya kampuni iliyoorodheshwa DSE kupitia pesa ya simu. Hakuna kwenda kwa dalali, hakuna kiwango cha chini cha hisa, hakuna kusubiri siku tatu kukamilika.",
  "Fee": "Ada",
  "From": "Kuanzia",
  "Live on CAPX · one CRDBt is one share in custody": "Inapatikana CAPX · CRDBt moja ni hisa moja iliyo kwenye dhamana",
  "Open an account, fund it from mobile money or your bank, and own a Tanzanian share the same day.": "Fungua akaunti, iweke pesa kutoka simu au benki yako, na umiliki hisa ya Tanzania siku hiyo hiyo.",
  "Settlement": "Ukamilishaji",
  "Tanzanian shares,": "Nunua Hisa za Tanzania,",
  "Expand your investment portfolio, invest in global companies in seconds.": "Panua uwekezaji wako, wekeza kwenye kampuni za dunia kwa sekunde chache.",
  "Buy and sell leading US stocks,": "Nunua na Kuuza hisa za Marekani,",
  "Own shares in leading US companies directly from your account.": "Miliki hisa za kampuni maarufu za Marekani moja kwa moja kutoka akaunti yako.",
  "US equities": "Hisa za Marekani",
  "Your shillings,": "Shilingi zako,",
  "at work on the DSE.": "zikifanya kazi DSE.",
  "directly from your account.": "moja kwa moja kutoka akaunti yako.",
  "traded 24/7, payout instant.": "masaa 24/7, malipo ni papo hapo.",
  "today": "leo",
  "fee": "ada",
  "settles same day in nTZS": "inakamilika siku hiyo hiyo kwa nTZS",
  "Account name": "Jina la akaunti",
  "Account number": "Namba ya akaunti",
  "Amount, exactly": "Kiasi, kamili",
  "Bank to select": "Benki ya kuchagua",
  "Copied": "Imenakiliwa",
  "Copy": "Nakili",
  "Get bank details for": "Pata maelezo ya benki kwa",
  "I have sent it": "Nimeshatuma",
  "Preparing…": "Inaandaliwa…",
  "Reference · put this in the description": "Kumbukumbu · iweke kwenye maelezo",
  "Send a bank transfer": "Tuma kwa benki",
  "Send from any Tanzanian bank. A different amount or a missing reference cannot be matched automatically.": "Tuma kutoka benki yoyote ya Tanzania. Kiasi tofauti au kukosa kumbukumbu hakuwezi kulinganishwa moja kwa moja.",
  "Sending prompt…": "Inatuma ombi…",
  "Valid until": "Inatumika hadi",
  "Waiting for payment": "Inasubiri malipo",
  "You will get an account and a reference to pay from your own bank app. Any Tanzanian bank works; it usually lands within about 10 minutes.": "Utapata akaunti na kumbukumbu ya kulipa kupitia programu ya benki yako. Benki yoyote ya Tanzania inafaa; kwa kawaida hufika ndani ya dakika 10 hivi.",
  "Minimum lot": "Kiwango cha chini",
  "None": "Hakuna",
  "from the DSE to Wall Street.": "kutoka DSE hadi Wall Street.",
  "One account, funded from mobile money or your bank. Own CRDB on the Dar es Salaam Stock Exchange the same day, and US names like NVIDIA and Apple alongside it.": "Akaunti moja, inayowekewa pesa kwa simu au benki yako. Miliki CRDB kwenye Soko la Hisa la Dar es Salaam siku hiyo hiyo, pamoja na kampuni za Marekani kama NVIDIA na Apple.",
  "DSE": "DSE",
  "in shillings": "kwa shilingi",
  "US stocks": "Hisa za Marekani",
  "names": "kampuni",
  "in dollars": "kwa dola",
  "Browse US stocks": "Tazama hisa za Marekani",
  "Send from the account you enter above. You will get an account and a reference to pay from your bank app; it usually lands within about 10 minutes.": "Tuma kutoka akaunti uliyoandika hapo juu. Utapata akaunti na kumbukumbu ya kulipa kupitia programu ya benki yako; kwa kawaida hufika ndani ya dakika 10 hivi.",
  "Send to a bank account": "Tuma kwenye akaunti ya benki",
  "Choose your bank": "Chagua benki yako",
  "Mobile money": "Pesa ya simu",
  "Bank": "Benki",
  "Listed on the Dar es Salaam Stock Exchange. One {sym}t is one share, held in custody.":
    "Imeorodheshwa kwenye Soko la Hisa la Dar es Salaam. {sym}t moja ni hisa moja, inayoshikiliwa kwa niaba yako.",
  "suspended": "imesimamishwa",
  // How it works, rewritten in plain language.
  "Sign up with your phone number, then verify who you are with a photo of your ID and a quick selfie. It takes a few minutes, and you only do it once.": "Jisajili kwa namba yako ya simu, kisha thibitisha utambulisho wako kwa picha ya kitambulisho na selfie fupi. Inachukua dakika chache, na unafanya mara moja tu.",
  "Add shillings": "Weka shilingi",
  "Top up from M-Pesa, Airtel Money, Tigo Pesa or any Tanzanian bank. Your balance is held in shillings, so there is no currency to convert and nothing to lose on an exchange rate.": "Weka pesa kupitia M-Pesa, Airtel Money, Tigo Pesa au benki yoyote ya Tanzania. Salio lako linabaki kwa shilingi, hivyo hakuna kubadilisha fedha wala hasara ya viwango vya kubadilishia.",
  "Buy a share": "Nunua hisa",
  "Pick a company — CRDB, NMB or others on the Dar es Salaam Stock Exchange, or well-known US names — and choose how much to spend. You do not need to buy a whole share: TSh 2,000 buys you a piece. The purchase is done the same day.": "Chagua kampuni — CRDB, NMB au nyingine kwenye Soko la Hisa la Dar es Salaam, au kampuni maarufu za Marekani — kisha chagua kiasi cha kutumia. Huhitaji kununua hisa nzima: TSh 2,000 inakununulia sehemu. Ununuzi unakamilika siku hiyo hiyo.",
  "Your shares are held safely for you": "Hisa zako zinahifadhiwa salama kwa ajili yako",
  "The real shares are held by a licensed DSE broker. Each one is matched by a digital record on a public ledger, one for one, so what CAPX holds can be checked by anyone at any time, not just taken on trust.": "Hisa halisi zinashikiliwa na dalali wa DSE mwenye leseni. Kila moja ina rekodi ya kidijitali kwenye daftari la umma, moja kwa moja, hivyo kile CAPX inachoshikilia kinaweza kukaguliwa na mtu yeyote wakati wowote, si kuaminiwa tu.",
  "See what is held": "Tazama kinachoshikiliwa",
  "Sell and withdraw whenever you like": "Uza na toa pesa wakati wowote",
  "Sell some or all of your shares and the shillings are back in your balance straight away. Withdraw to your mobile money or bank account in a couple of taps.": "Uza baadhi au hisa zako zote na shilingi zinarudi kwenye salio lako mara moja. Toa pesa kwenda simu au akaunti ya benki kwa kubofya mara chache.",
  "What does it cost?": "Inagharimu kiasi gani?",
  "2.5% when you buy and 2.5% when you sell — 1% of that goes to the licensed broker that holds the shares. There is no account fee and no monthly charge. Mobile money and bank transfers may carry the network's own small fee, and you always see it before you confirm.":
    "2.5% unaponunua na 2.5% unapouza — kati ya hizo, 1% huenda kwa dalali mwenye leseni anayeshikilia hisa. Hakuna ada ya akaunti wala malipo ya kila mwezi. Pesa ya simu na uhamisho wa benki huenda zikawa na ada ndogo ya mtandao, na unaiona kila mara kabla ya kuthibitisha.",
  "Is my share a real share?": "Je, hisa yangu ni hisa halisi?",
  "Yes. Every CRDB or NMB share in your account is a real share held for you by a licensed broker, and CAPX never sells more than it holds. You can see the totals on the proof page whenever you want.": "Ndiyo. Kila hisa ya CRDB au NMB kwenye akaunti yako ni hisa halisi inayoshikiliwa kwa ajili yako na dalali mwenye leseni, na CAPX haiuzi zaidi ya inachoshikilia. Unaweza kuona jumla kwenye ukurasa wa uthibitisho wakati wowote.",
  "What happens when I sell?": "Nini kinatokea ninapouza?",
  "CAPX buys the shares back from you at the current price and puts the shillings, less the 2.5% fee, into your balance immediately. Those shares go back into CAPX's stock, ready for the next buyer.": "CAPX inanunua hisa hizo kutoka kwako kwa bei ya sasa na kuweka shilingi, ukiondoa ada ya 2.5%, kwenye salio lako mara moja. Hisa hizo zinarudi kwenye akiba ya CAPX, tayari kwa mnunuzi anayefuata.",
  "Where do the prices come from?": "Bei zinatoka wapi?",
  "Tanzanian shares use the Dar es Salaam Stock Exchange's own prices, updated through the trading day. US shares follow their US market price. You pay the price shown, not a hidden markup.": "Hisa za Tanzania zinatumia bei za Soko la Hisa la Dar es Salaam lenyewe, zinazosasishwa katika siku ya biashara. Hisa za Marekani zinafuata bei ya soko la Marekani. Unalipa bei inayoonyeshwa, bila nyongeza iliyofichwa.",
  "Can I buy less than one share?": "Naweza kununua chini ya hisa moja?",
  "Yes. You choose the amount in shillings and get that share of a share. It makes it possible to start small and add as you go.": "Ndiyo. Unachagua kiasi kwa shilingi na unapata sehemu hiyo ya hisa. Inakuwezesha kuanza kidogo na kuongeza kadri unavyoendelea.",
  "Who can use CAPX?": "Nani anaweza kutumia CAPX?",
  "Anyone in Tanzania with a valid ID, a phone number and a mobile money or bank account. US shares are not available to US persons. Share prices go up and down, and nothing here is investment advice.": "Mtu yeyote Tanzania mwenye kitambulisho halali, namba ya simu na akaunti ya pesa ya simu au benki. Hisa za Marekani hazipatikani kwa raia wa Marekani. Bei za hisa hupanda na kushuka, na hakuna kilichoandikwa hapa ni ushauri wa uwekezaji.",
  "From shillings": "Kutoka shilingi",
  "to shares.": "hadi hisa.",
  "Five steps, a few minutes, and a phone. Here is what happens at each one.": "Hatua tano, dakika chache, na simu. Hiki ndicho kinachotokea kila hatua.",
  "Check it yourself": "Kagua mwenyewe",
  "For the curious: every company on CAPX has a public address where its shares can be counted. Tap one to see it.": "Kwa wadadisi: kila kampuni kwenye CAPX ina anwani ya umma ambapo hisa zake zinaweza kuhesabiwa. Bofya moja kuiona.",
  "These records live on Base, a public network. Nobody, including CAPX, can change what they say without everyone seeing.": "Rekodi hizi ziko kwenye Base, mtandao wa umma. Hakuna mtu, ikiwemo CAPX, anayeweza kubadilisha kilichoandikwa bila kila mtu kuona.",
  "And more": "Na zaidi",
  "US equities, from the same account": "Hisa za Marekani, kutoka akaunti hiyo hiyo",
  "Add": "Weka",
  "Withdrawals start at": "Kutoa pesa kunaanzia",
  "Return shows after your first buy": "Faida inaonekana baada ya ununuzi wako wa kwanza",
  "Tanzania": "Tanzania",
  "US": "Marekani",
  "Movers": "Zinazosonga",
  "United States": "Marekani",
  "Tanzanian shares in shillings, US shares in dollars.": "Hisa za Tanzania kwa shilingi, hisa za Marekani kwa dola.",
  "Prices update live. US shares are not available to US persons.": "Bei zinasasishwa moja kwa moja. Hisa za Marekani hazipatikani kwa raia wa Marekani.",
  "Contract details": "Maelezo ya mkataba",
  "Last price": "Bei ya mwisho",
  "DSE data is temporarily unavailable.": "Taarifa za DSE hazipatikani kwa muda.",
  "This is the last price CAPX published": "Hii ni bei ya mwisho iliyochapishwa na CAPX",
  "Buying and selling continue at this price.": "Kununua na kuuza kunaendelea kwa bei hii.",
  "The DSE's price history is unavailable right now. The chart returns as soon as the exchange is back.": "Historia ya bei ya DSE haipatikani sasa hivi. Chati itarudi mara soko litakaporejea.",
  "First price published by CAPX on": "Bei ya kwanza iliyochapishwa na CAPX tarehe",
  "The chart fills in day by day, and shows the full DSE history once the exchange is back.": "Chati itajaa siku baada ya siku, na itaonyesha historia kamili ya DSE soko likirejea.",

  // --- footer ---
  "Invest": "Wekeza",
  "Company": "Kampuni",
  // Bank names, left as they are said.
  "CRDB Bank": "CRDB Bank",
  "NMB Bank": "NMB Bank",
  "Public markets, rebuilt as open infrastructure. Priced by live oracles, held in your own wallet.":
    "Masoko ya umma, yaliyojengwa upya kama miundombinu huria. Bei kutoka oracle za moja kwa moja, zinashikiliwa kwenye mkoba wako mwenyewe.",
  "CAPX lets you buy shares listed on the Dar es Salaam Stock Exchange, and US shares, with Tanzanian shillings. Shares bought through a CAPX account are held on your behalf by CAPX with a licensed DSE broker. What you hold is a representation of the underlying share on the blockchain, held by a custodian or a special purpose vehicle, rather than registered shareholding. Tanzanian shares carry no dividend entitlement; US shares reflect dividends through the token's on-chain multiplier. Neither carries voting or other shareholder rights. CAPX is not an exchange or an investment adviser, and nothing here is investment advice. Share prices can fall as well as rise. US shares are not available to US persons.":
    "CAPX inakuwezesha kununua hisa zilizoorodheshwa kwenye Soko la Hisa la Dar es Salaam, na hisa za Marekani, kwa shilingi za Tanzania. Hisa zinazonunuliwa kupitia akaunti ya CAPX zinashikiliwa kwa niaba yako na CAPX pamoja na dalali wa DSE mwenye leseni. Unachoshikilia ni uwakilishi wa hisa husika kwenye blockchain, unaoshikiliwa na mtunzaji au kampuni maalum, si umiliki uliosajiliwa. Hisa za Tanzania hazina haki ya gawio; hisa za Marekani zinaakisi gawio kupitia kizidishi cha tokeni kwenye blockchain. Hakuna kati yao inayotoa haki ya kupiga kura au haki nyingine za mwanahisa. CAPX si soko la hisa wala mshauri wa uwekezaji, na hakuna chochote hapa ni ushauri wa uwekezaji. Bei za hisa zinaweza kushuka au kupanda. Hisa za Marekani hazipatikani kwa raia wa Marekani.",
  // The brand tagline, kept as it is said rather than translated literally.
  // Standing orders.
  // Push notifications.
  "I am not sending this one": "Sitatuma hii",
  "My bank is not listed": "Benki yangu haipo kwenye orodha",
  "Bank code, e.g. NBC": "Msimbo wa benki, mfano NBC",
  "Change the password you sign in with.": "Badilisha nenosiri unalotumia kuingia.",
  "Current password": "Nenosiri la sasa",
  "New password": "Nenosiri jipya",
  "Change password": "Badilisha nenosiri",
  "Changing…": "Inabadilisha…",
  "Password changed.": "Nenosiri limebadilishwa.",
  "Could not change your password": "Imeshindikana kubadilisha nenosiri",
  "Max": "Kiwango cha juu",
  "Someone bought": "Mtu amenunua",
  "Someone sold": "Mtu ameuza",
  "just now": "sasa hivi",
  "ago": "iliyopita",
  "Notifications": "Arifa",
  "Deposits, fills, and your portfolio morning and evening.":
    "Amana, manunuzi, na taarifa ya mali yako asubuhi na jioni.",
  "Add CAPX to your Home Screen first, then turn these on from there.":
    "Kwanza ongeza CAPX kwenye skrini yako ya kwanza, kisha uwashe arifa hapo.",
  "Your browser is blocking notifications for CAPX. Allow them in its settings to turn these on.":
    "Kivinjari chako kimezuia arifa za CAPX. Ziruhusu kwenye mipangilio yake ili kuwasha.",
  "Turn on": "Washa",
  "Turning on…": "Inawasha…",
  "Turn off": "Zima",
  "Send a test": "Tuma jaribio",
  "Notifications are on for this device.": "Arifa zimewashwa kwa kifaa hiki.",
  "Notifications are off for this device.": "Arifa zimezimwa kwa kifaa hiki.",
  "Could not turn on notifications": "Imeshindikana kuwasha arifa",
  "Could not turn off notifications": "Imeshindikana kuzima arifa",
  "Could not send a test": "Imeshindikana kutuma jaribio",
  "Sent. It should appear in a moment.": "Imetumwa. Itaonekana hivi punde.",
  "Nothing was sent to this account.": "Hakuna kilichotumwa kwa akaunti hii.",
  "All paused. Tap to see them.": "Zote zimesimamishwa. Gusa kuziona.",
  "You hold": "Unamiliki",
  "Automatic investing": "Uwekezaji wa kiotomatiki",
  "Invest on payday, every payday.": "Wekeza siku ya mshahara, kila mshahara.",
  "Set an amount and a day, and CAPX buys for you — weekly or monthly, in any listed share. It spends only what is already in your account, and you can pause it whenever you like.":
    "Weka kiasi na siku, na CAPX itanunua kwa niaba yako — kila wiki au kila mwezi, katika hisa yoyote iliyoorodheshwa. Hutumia tu kilichopo kwenye akaunti yako, na unaweza kusimamisha wakati wowote.",
  "For example": "Kwa mfano",
  "on the 1st of each month": "tarehe 1 ya kila mwezi",
  "Buy the same amount on the same day, without thinking about it.":
    "Nunua kiasi kilekile siku ileile, bila kufikiria.",
  "New plan": "Mpango mpya",
  "Close": "Funga",
  "Share": "Hisa",
  "Amount each time": "Kiasi kila mara",
  "Try it": "Ijaribu",
  "Daily": "Kila siku",
  "Weekly": "Kila wiki",
  "Monthly": "Kila mwezi",
  "every week": "kila wiki",
  "every month": "kila mwezi",
  "Each time": "Kila mara",
  "In a year": "Kwa mwaka",
  "At today's price of": "Kwa bei ya leo ya",
  "a share. Fractions are fine — you never have to buy a whole one.":
    "kwa hisa. Sehemu ya hisa inakubalika — huhitaji kununua hisa nzima.",
  "Every day": "Kila siku",
  "every day": "kila siku",
  "Every morning at 9am, on the days the market trades. The trade fee applies each time, so a small daily amount costs more in fees than the same money once a month.":
    "Kila asubuhi saa tatu, siku ambazo soko linafanya kazi. Ada ya manunuzi hutozwa kila mara, hivyo kiasi kidogo cha kila siku hugharimu ada zaidi kuliko fedha hizohizo mara moja kwa mwezi.",
  "Every week": "Kila wiki",
  "Every month": "Kila mwezi",
  "Day": "Siku",
  "Day of the month": "Tarehe ya mwezi",
  "The 28th is the last day offered, so every month has one.":
    "Tarehe 28 ndiyo ya mwisho inayotolewa, ili kila mwezi iwe nayo.",
  "Start plan": "Anza mpango",
  "It spends the shillings already in your account. If the balance is short that day, nothing is bought and we tell you.":
    "Hutumia shilingi zilizopo kwenye akaunti yako. Kama salio halitoshi siku hiyo, hakuna kinachonunuliwa na tutakujulisha.",
  "Could not save your plan": "Imeshindikana kuhifadhi mpango wako",
  "Pause": "Simamisha",
  "Resume": "Endelea",
  "every": "kila",
  "day": "tarehe",
  "of each month": "ya kila mwezi",
  "next": "ifuatayo",
  "paused": "imesimamishwa",
  "bought": "zimenunuliwa",
  "last": "mwisho",
  "Sunday": "Jumapili",
  "Monday": "Jumatatu",
  "Tuesday": "Jumanne",
  "Wednesday": "Jumatano",
  "Thursday": "Alhamisi",
  "Friday": "Ijumaa",
  "Saturday": "Jumamosi",
  "Capital in Motion": "Capital in Motion",

  // --- account creation (AccountForm, JoinFlow) ---
  // The onboarding funnel had no translation coverage at all until now; it is
  // the one place a new customer cannot fall back to fluent English if the
  // rest of the site is read in Swahili. The consent sentence is legal text —
  // worth the same native-reviewer pass the file header already asks for.
  "New account": "Akaunti mpya",
  "Email or username": "Barua pepe au jina la mtumiaji",
  "Password": "Nenosiri",
  "10+ characters, letters and numbers": "Herufi 10+, herufi na namba",
  "Username": "Jina la mtumiaji",
  "optional": "si lazima",
  "Optional — 3 characters or more": "Si lazima — herufi 3 au zaidi",
  "Saved as": "Itahifadhiwa kama",
  "Use": "Tumia",
  "Full name": "Jina kamili",
  "As on your NIDA": "Kama ilivyo kwenye NIDA yako",
  "20 digits": "Tarakimu 20",
  "e.g. AB123456": "mfano AB123456",
  "Password looks good": "Nenosiri ni zuri",
  "Both photos attached. They go to verification as soon as your account is open.":
    "Picha zote mbili zimeambatishwa. Zinakwenda kwa uthibitishaji mara akaunti yako itakapofunguliwa.",
  "Needed to verify the account. You can add them later, but you will not be able to trade until they are checked.":
    "Zinahitajika kuthibitisha akaunti. Unaweza kuziongeza baadaye, lakini hutaweza kufanya biashara mpaka zikaguliwe.",
  "I have read and agree to the": "Nimesoma na ninakubali",
  "terms of service": "masharti ya huduma",
  "and": "na",
  "privacy policy": "sera ya faragha",
  ", and I am not a United States person.": ", na mimi si raia wa Marekani.",
  "Working…": "Inafanya kazi…",
  "Create account": "Fungua akaunti",
  "Could not continue": "Imeshindwa kuendelea",
  "Something went wrong": "Hitilafu imetokea",
  "Shillings in.": "Weka shilingi.",
  "Shares out.": "Pata hisa.",
  "Send shillings from your phone and buy tokenized equities. No wallet, no seed phrase, nothing to convert. CAPX holds the assets for you and records what you are owed.":
    "Tuma shilingi kutoka kwenye simu yako kisha ununue hisa za kidijitali. Hakuna mkoba, hakuna seed phrase, hakuna cha kubadilisha. CAPX inashikilia mali kwa niaba yako na kurekodi unachodai.",
  "Account open": "Akaunti imefunguliwa",
  "Create your account": "Fungua akaunti yako",
  "Signed in as": "Umeingia kama",
  "You’ll get a prompt on your phone. Approve it and your balance appears here, CAPX handles the conversion.":
    "Utapata ombi kwenye simu yako. Likubali na salio lako litaonekana hapa, CAPX hushughulikia ubadilishaji.",
  "min 500": "kiwango cha chini 500",
  "You send shillings.": "Unatuma shilingi.",
  "Your shillings become USDC at the live rate.": "Shilingi zako zinabadilika kuwa USDC kwa kiwango cha wakati huo.",
  "Your balance appears.": "Salio lako linaonekana.",
  "Buying only for now.": "Kwa sasa ni kununua tu.",
  "Selling opens when the offer closes and allocation completes.": "Kuuza kutafunguliwa ofa itakapofungwa na mgawo kukamilika.",
  "Held by CAPX": "Inashikiliwa na CAPX",
  "Token issued by": "Tokeni imetolewa na",
  "Selling": "Kuuza",
  "Opens when the offer closes": "Kutafunguliwa ofa itakapofungwa",
  "Open": "Wazi",
  "CAPX buys this token and holds it. The balance above is read from Base, and customers' claims are recorded in CAPX's ledger.": "CAPX inanunua tokeni hii na kuishikilia. Salio hapo juu linasomwa kutoka Base, na madai ya wateja yameandikwa kwenye daftari la CAPX.",
  "IPO": "IPO",
  "Tokenised": "Imetokenishwa",
  "An offer tokenised by {issuer}. CAPX buys the token, holds it, and prices it in shillings; your balance is a claim on what CAPX holds.": "Ofa iliyotokenishwa na {issuer}. CAPX inanunua tokeni, inaishikilia, na kuipanga bei kwa shilingi; salio lako ni dai juu ya kile CAPX inachoshikilia.",
  "its issuer": "mtoaji wake",
  "Open offer — buying only.": "Ofa iko wazi — kununua tu.",
  "Selling opens when the offer closes and allocation completes. The price is set by CAPX, not by an exchange.": "Kuuza kutafunguliwa ofa itakapofungwa na mgawo kukamilika. Bei inapangwa na CAPX, si soko la hisa.",
  "CAPX sets this price. A chart builds from each price CAPX publishes.": "CAPX inapanga bei hii. Chati inajengwa kutoka kila bei CAPX inayochapisha.",
  "The chart fills in day by day as CAPX republishes it.": "Chati itajaa siku baada ya siku CAPX inapochapisha upya.",
  "Cover": "Ufunikaji",
  "Covered": "Imefunikwa",
  "Short": "Pungufu",
  "Set by CAPX": "Imewekwa na CAPX",
  "Tokenised by {issuer}. CAPX buys and holds the token, and prices it in shillings.": "Imetokenishwa na {issuer}. CAPX inanunua na kushikilia tokeni, na kuipanga bei kwa shilingi.",
  "Verification under review.": "Uhakiki unapitiwa.",
  "Verify your identity to buy.": "Thibitisha utambulisho wako ili ununue.",
  "You can buy as soon as it is approved. Selling stays open.": "Utaweza kununua mara tu utakapoidhinishwa. Kuuza kunabaki wazi.",
  "It takes a few minutes.": "Inachukua dakika chache.",
};
