/**
 * Swahili, keyed by the English it replaces.
 *
 * Written for Tanzanian usage rather than textbook Swahili: "hisa" for shares,
 * "salio" for balance, "weka pesa" for a deposit, because that is what a
 * customer reading this already says. Financial and legal wording is the part
 * most worth a native reviewer's eye before this carries real volume.
 *
 * A missing entry falls through to English on purpose. Half a sentence in each
 * language is worse than a whole one in the wrong language.
 */
export const SW: Record<string, string> = {
  // --- navigation ---
  "Markets": "Masoko",
  "Portfolio": "Uwekezaji",
  "How it works": "Jinsi inavyofanya kazi",
  "Open account": "Fungua akaunti",
  "Open an account": "Fungua akaunti",
  "Sign in": "Ingia",
  "Sign out": "Toka",
  "Home": "Mwanzo",
  "Account": "Akaunti",
  "Settings": "Mipangilio",
  "All markets": "Masoko yote",

  // --- hero and landing ---
  "Own the open": "Miliki soko",
  "market.": "huria.",
  "US shares in dollars. Tanzanian shares in shillings. Settled against custody published on Base.":
    "Hisa za Marekani kwa dola. Hisa za Tanzania kwa shilingi. Hulipwa dhidi ya dhamana iliyochapishwa kwenye Base.",
  "Explore markets": "Tazama masoko",
  "Onchain value": "Thamani ya mnyororo",
  "Dar es Salaam": "Dar es Salaam",
  "buy in shillings": "nunua kwa shilingi",

  // --- the ticket ---
  "You pay": "Unalipa",
  "Buy": "Nunua",
  "Sell": "Uza",
  "You receive": "Unapokea",
  "Shares": "Hisa",
  "Shares sold": "Hisa zilizouzwa",
  "Price": "Bei",
  "Total cost": "Gharama jumla",
  "You receive ": "Unapokea ",
  "Spend (TZS)": "Tumia (TZS)",
  "Shares to sell": "Hisa za kuuza",
  "Receive about (TZS)": "Utapokea takriban (TZS)",
  "By amount": "Kwa kiasi",
  "By shares": "Kwa hisa",
  "All": "Zote",
  "Buy CRDB": "Nunua CRDB",
  "Sell CRDB": "Uza CRDB",
  "Placing…": "Inatuma…",
  "Indicative. Real quote on the": "Ni makadirio. Bei halisi iko kwenye",
  "asset page": "ukurasa wa hisa",
  "TZS a share": "TZS kwa hisa",
  "Dar es Salaam Stock Exchange": "Soko la Hisa la Dar es Salaam",
  "DSE live": "DSE moja kwa moja",
  "DSE close": "Bei ya kufunga DSE",
  "Proof of reserves": "Uthibitisho wa akiba",
  "Add money": "Weka pesa",
  "Buy shares": "Nunua hisa",
  "Sell shares": "Uza hisa",
  "Withdraw": "Toa pesa",

  // --- portfolio and wallet ---
  "Your book.": "Mali zako.",
  "Cash": "Pesa",
  "Total value": "Thamani jumla",
  "Return": "Faida",
  "held by CAPX": "inashikiliwa na CAPX",
  "Available to invest": "Pesa za kuwekeza",
  "each spent in its own currency": "kila moja hutumika kwa sarafu yake",
  "in shares": "katika hisa",
  "Bought": "Umenunua",
  "Sold": "Umeuza",
  "Activity": "Shughuli",
  "Clear": "Futa",
  "Nothing yet. Add money to get started.": "Bado hakuna kitu. Weka pesa ili kuanza.",
  "after your first buy": "baada ya ununuzi wako wa kwanza",
  "Wallet": "Mkoba",
  "How you are paying": "Unalipaje",
  "Amount": "Kiasi",
  "Amount in shillings": "Kiasi kwa shilingi",
  "Amount to withdraw": "Kiasi cha kutoa",
  "Send to mobile money": "Tuma kwenye simu ya pesa",
  "Sending to": "Inatumwa kwa",
  "They receive": "Watapokea",
  "Bank account you are sending from": "Akaunti ya benki unayotumia kutuma",
  "You have no shares to sell yet": "Bado huna hisa za kuuza",
  "Deposit": "Amana",
  "Proceeds": "Mapato",
  "Paid": "Imelipwa",
  "invested": "zimewekezwa",

  // --- verification ---
  "Verification": "Uthibitishaji",
  "Verify your identity to keep using your account.":
    "Thibitisha utambulisho wako ili uendelee kutumia akaunti yako.",
  "Verify now": "Thibitisha sasa",
  "Try again": "Jaribu tena",
  "Your verification is being reviewed. Nothing to do.":
    "Uthibitishaji wako unakaguliwa. Hakuna la kufanya.",
  "Verification was not accepted. Please submit again.":
    "Uthibitishaji haukukubaliwa. Tafadhali wasilisha tena.",
  "Confirm it’s you.": "Thibitisha ni wewe.",
  "Two photographs: the document you hold, and you holding the phone. It takes about a minute and only has to be done once.":
    "Picha mbili: hati uliyo nayo, na wewe ukiwa umeshika simu. Inachukua takriban dakika moja na hufanyika mara moja tu.",
  "Your document.": "Hati yako.",
  "Your document": "Hati yako",
  "A photo of you, now": "Picha yako, sasa hivi",
  "A photo of you, now.": "Picha yako, sasa hivi.",
  "National ID (NIDA)": "Kitambulisho cha Taifa (NIDA)",
  "Passport": "Paspoti",
  "Driver's licence": "Leseni ya udereva",
  "Voter's card": "Kadi ya mpiga kura",
  "Document number (optional)": "Namba ya hati (si lazima)",
  "Photograph or upload your document (JPEG, PNG or PDF)":
    "Piga picha au pakia hati yako (JPEG, PNG au PDF)",
  "That file is too large. The limit is 6MB.": "Faili hilo ni kubwa mno. Kikomo ni MB 6.",
  "That file could not be read. Try a JPEG, PNG or PDF.":
    "Faili hilo halikusomeka. Jaribu JPEG, PNG au PDF.",
  "Document attached.": "Hati imeambatishwa.",
  "Replace": "Badilisha",
  "Photo taken.": "Picha imepigwa.",
  "Retake": "Piga tena",
  "Open camera": "Fungua kamera",
  "Take photo": "Piga picha",
  "Cancel": "Ghairi",
  "Taken here rather than uploaded, so it matches the document.":
    "Inapigwa hapa badala ya kupakiwa, ili ilingane na hati.",
  "Camera access was refused. Allow it in your browser settings and try again.":
    "Ruhusa ya kamera ilikataliwa. Iruhusu kwenye mipangilio ya kivinjari kisha ujaribu tena.",
  "Submit for verification": "Wasilisha kwa uthibitishaji",
  "Submitting…": "Inawasilisha…",
  "Submitted": "Imewasilishwa",
  "Thanks. We’ll take a look.": "Asante. Tutaiangalia.",
  "Verified": "Imethibitishwa",
  "Under review": "Inakaguliwa",
  "Not accepted": "Haikukubaliwa",
  "Not started": "Haijaanza",
  "Verify your account": "Thibitisha akaunti yako",
  "Verify your identity": "Thibitisha utambulisho wako",
  "Your identity has been confirmed. Nothing more to do here.":
    "Utambulisho wako umethibitishwa. Hakuna zaidi la kufanya hapa.",
  "Your verification is being reviewed. You can keep going below while we look at it.":
    "Uthibitishaji wako unakaguliwa. Unaweza kuendelea hapa chini wakati tunauangalia.",
  "Open your account first, then we will confirm who you are.":
    "Fungua akaunti yako kwanza, kisha tutathibitisha wewe ni nani.",
  "Identity document": "Hati ya utambulisho",
  "National ID": "Kitambulisho cha Taifa",
  "NIDA number": "Namba ya NIDA",
  "Passport number": "Namba ya paspoti",
  "Licence number": "Namba ya leseni",
  "Voter number": "Namba ya mpiga kura",
  "Submit again": "Wasilisha tena",
  "View status": "Angalia hali",

  // --- settings ---
  "Your account.": "Akaunti yako.",
  "Display name": "Jina la kuonyesha",
  "Mobile money number": "Namba ya simu ya pesa",
  "Used for deposits and withdrawals.": "Hutumika kwa amana na kutoa pesa.",
  "Save changes": "Hifadhi mabadiliko",
  "Saving…": "Inahifadhi…",
  "Email": "Barua pepe",
  "Country": "Nchi",
  "Twenty digits. Must match the document you submit for verification.":
    "Tarakimu ishirini. Lazima ilingane na hati utakayowasilisha kwa uthibitishaji.",
  "Verified and locked to the document we checked.":
    "Imethibitishwa na imefungwa kwenye hati tuliyokagua.",
  "Language": "Lugha",
  "Tap feedback": "Mrejesho wa kugusa",
  "Click on": "Mlio umewashwa",
  "Click off": "Mlio umezimwa",
  "This iPhone is older than iOS 17.4, which is the first version a website can use the Taptic Engine. A short click can be played instead. It is sound, not vibration.":
    "iPhone hii ni ya zamani kuliko iOS 17.4, ambayo ndiyo toleo la kwanza tovuti inaweza kutumia Taptic Engine. Badala yake mlio mfupi unaweza kupigwa. Ni sauti, si mtetemo.",
  "Legal": "Kisheria",
  "These terms describe how CAPX actually operates today. They have not yet been reviewed by a licensed Tanzanian advocate, and will be updated when they are. If anything here conflicts with Tanzanian law, the law applies.":
    "Masharti haya yanaeleza jinsi CAPX inavyofanya kazi leo. Bado hayajakaguliwa na wakili aliyesajiliwa Tanzania, na yatasasishwa yatakapokaguliwa. Kama kitu chochote hapa kinapingana na sheria za Tanzania, sheria ndiyo inayotumika.",
  "Terms of service": "Masharti ya huduma",
  "Privacy policy": "Sera ya faragha",

  // --- money and errors ---
  "Your balance is": "Salio lako ni",
  "You need": "Unahitaji",
  "more.": "zaidi.",
  "Could not reach the server. Nothing was placed.":
    "Imeshindwa kufikia seva. Hakuna agizo lililotumwa.",
  "Could not reach the server.": "Imeshindwa kufikia seva.",
  "Loading…": "Inapakia…",
  // --- how it works ---
  // Technical nouns stay in English where that is how they are actually said:
  // Chainlink, B20, multiplier, oracle. Borrowing them is natural Swahili here,
  // and inventing translations would make the page harder to read, not easier.
  "No black box.": "Hakuna siri.",
  "Just addresses.": "Ni anwani tu.",
  "CAPX is a thin, honest interface over machinery that already exists on Base. Here is exactly what it reads, and where you can check it yourself.":
    "CAPX ni kiolesura chepesi na cha kweli juu ya mfumo ambao tayari upo kwenye Base. Haya ndiyo hasa inayosoma, na mahali unapoweza kuthibitisha mwenyewe.",
  "Contracts CAPX reads": "Mikataba ambayo CAPX inasoma",
  "Straight answers": "Majibu ya moja kwa moja",
  "Base documentation": "Nyaraka za Base",
  "Every B20 address begins 0xb2. They are native precompiles on Base, not deployed bytecode.":
    "Kila anwani ya B20 huanza na 0xb2. Ni precompiles za asili kwenye Base, si bytecode iliyosambazwa.",

  "The issuer mints a B20 token": "Mtoaji hutengeneza tokeni ya B20",
  "A regulated issuer holds the underlying share and mints a matching B20 token on Base. B20 extends ERC-20 for real-world assets and is asset-agnostic. These tokens are native precompiles rather than separately deployed contracts, audited by Base and Spearbit with ongoing Cantina and HackerOne bounty coverage.":
    "Mtoaji aliyesajiliwa hushika hisa halisi na kutengeneza tokeni ya B20 inayolingana kwenye Base. B20 huongeza ERC-20 kwa ajili ya mali halisi na haijafungwa kwa aina moja ya mali. Tokeni hizi ni precompiles za asili badala ya mikataba iliyosambazwa peke yake, zilizokaguliwa na Base na Spearbit, na zina ulinzi endelevu wa zawadi kupitia Cantina na HackerOne.",

  "Chainlink publishes a total-return mark": "Chainlink huchapisha bei ya total-return",
  "Each asset has a Chainlink feed on Base reporting price × multiplier, WAD-scaled, running 24/5 and freezing through corporate actions. CAPX reads updatedAt on every round and flags a feed that has missed a session instead of showing you a confident number that isn't.":
    "Kila mali ina Chainlink feed kwenye Base inayoripoti bei × multiplier, kwa kipimo cha WAD, ikifanya kazi saa 24 kwa siku 5 na kusimama wakati wa maamuzi ya kampuni. CAPX husoma updatedAt kwa kila raundi na huonyesha alama pale feed imekosa kipindi, badala ya kukuonyesha namba inayoonekana ya uhakika kumbe si kweli.",

  "Corporate actions move the multiplier": "Maamuzi ya kampuni hubadilisha multiplier",
  "Splits and dividends do not rewrite balances. They adjust a WAD-precision multiplier, so one token is not permanently one share. CAPX applies the current multiplier everywhere a share count appears: portfolio quantities use scaledBalanceOf, and supply figures are multiplier-adjusted share-equivalents.":
    "Kugawanya hisa na gawio havibadilishi salio lako. Hurekebisha multiplier ya usahihi wa WAD, hivyo tokeni moja si hisa moja milele. CAPX hutumia multiplier ya sasa kila mahali idadi ya hisa inapoonekana: idadi za uwekezaji hutumia scaledBalanceOf, na takwimu za ugavi ni sawa na hisa baada ya kurekebishwa kwa multiplier.",

  "Policies gate transfers, not holding": "Sera hudhibiti uhamishaji, si umiliki",
  "Onchain policy registries enforce allowlists and blocklists, and a transfer to a sanctioned address reverts. Holding and secondary transfer are otherwise permissionless. KYC applies at mint and redeem with the issuer, not between wallets.":
    "Rejista za sera kwenye mnyororo hutekeleza orodha za kuruhusu na kuzuia, na uhamishaji kwenda anwani iliyozuiwa hukataliwa. Vinginevyo, kushika na kuhamisha hisa hakuhitaji ruhusa. KYC hutumika wakati wa kutengeneza na kukomboa na mtoaji, si kati ya pochi na pochi.",

  "CAPX reads, you sign": "CAPX husoma, wewe unasaini",
  "Prices, supply and balances are read straight from Base. Trades are routed by aggregating every venue on the chain: Aerodrome concentrated liquidity, Uniswap v3 and v4, PancakeSwap, because equity liquidity moves between them and no single pool tells the truth. Every fill is checked against the Chainlink mark before it is offered, and CAPX refuses to route anything more than 15% away from it.":
    "Bei, ugavi na salio husomwa moja kwa moja kutoka Base. Biashara hupitishwa kwa kukusanya kila soko kwenye mnyororo: Aerodrome concentrated liquidity, Uniswap v3 na v4, PancakeSwap, kwa sababu ukwasi wa hisa husogea kati yao na hakuna dimbwi moja linalosema ukweli wote. Kila biashara hukaguliwa dhidi ya bei ya Chainlink kabla ya kutolewa, na CAPX hukataa kupitisha lolote lililo zaidi ya asilimia 15 kutoka kwake.",

  "Is one token one share?": "Je, tokeni moja ni hisa moja?",
  "No. Redemption applies the current onchain multiplier, which absorbs splits and dividends. CAPX shows the multiplier on every asset page and adjusts every share count it displays.":
    "Hapana. Ukombozi hutumia multiplier ya sasa kwenye mnyororo, ambayo huchukua kugawanya hisa na gawio. CAPX huonyesha multiplier kwenye kila ukurasa wa hisa na hurekebisha kila idadi ya hisa inayoonyesha.",

  "Why does an asset show zero onchain supply?": "Kwa nini hisa fulani inaonyesha ugavi sifuri kwenye mnyororo?",
  "The Chainlink feed is live for all thirteen assets, but tokens are only minted as demand arrives. A supply of zero means nothing has been minted on Base yet. The mark is still real, there is just nothing to trade against.":
    "Chainlink feed inafanya kazi kwa hisa zote kumi na tatu, lakini tokeni hutengenezwa pale mahitaji yanapofika. Ugavi wa sifuri maana yake hakuna kilichotengenezwa kwenye Base bado. Bei bado ni halisi, ila hakuna cha kufanyia biashara.",

  "Why can't I trade every asset?": "Kwa nini siwezi kufanya biashara ya kila hisa?",
  "Secondary trading needs minted supply and a venue holding it. Four assets route today at roughly the oracle mark; the rest have nothing minted on Base yet, so CAPX marks them mint-only rather than inventing a fill. The markets table labels each one.":
    "Biashara ya pili inahitaji ugavi uliotengenezwa na soko linaloushika. Hisa nne zinapitishwa leo karibu na bei ya oracle; zilizobaki hazina kilichotengenezwa kwenye Base bado, hivyo CAPX huziweka alama ya kutengeneza tu badala ya kubuni biashara. Jedwali la masoko huweka alama kwa kila moja.",

  "Who can use this?": "Nani anaweza kutumia hii?",
  "Tokenized equities are not available to US persons. Connect your own wallet and CAPX holds nothing. Fund an account with Tanzanian shillings and CAPX holds those assets for you, recording your entitlement in its own ledger. That is custody, and it is the trade-off for not needing a wallet. Nothing here is investment advice.":
    "Hisa za kidijitali hazipatikani kwa watu wa Marekani. Unganisha pochi yako mwenyewe na CAPX haishiki chochote. Weka pesa kwa shilingi za Tanzania na CAPX hushika mali hizo kwa niaba yako, ikirekodi haki yako kwenye daftari lake. Hiyo ni udhamini, na ndiyo bei ya kutohitaji pochi. Hakuna chochote hapa ni ushauri wa uwekezaji.",

  "oracle-implied": "kwa makadirio ya oracle",
  "Review": "Kagua",
  "order": "agizo",
  "Search company or ticker": "Tafuta kampuni au alama",
  "Shillings": "Shilingi",
  "Tradeable": "Inanunulika",
  "No company matches": "Hakuna kampuni inayolingana",

  // --- remaining interface ---
  "A message from CAPX": "Ujumbe kutoka CAPX",
  "Amount (TZS)": "Kiasi (TZS)",
  "Approve the prompt on your phone. No card, no bank transfer.": "Kubali ujumbe kwenye simu yako. Hakuna kadi, hakuna uhamisho wa benki.",
  "Assets": "Mali",
  "Available": "Zinapatikana",
  "Available to buy": "Zinazopatikana kununua",
  "B20 precision": "Usahihi wa B20",
  "Biggest drawdowns": "Zilizoshuka zaidi",
  "Buy Tanzanian shares in shillings, settled in nTZS": "Nunua hisa za Tanzania kwa shilingi, hulipwa kwa nTZS",
  "By sector": "Kwa sekta",
  "CAPX Equities": "CAPX Equities",
  "CAPX Feeds": "CAPX Feeds",
  "CAPX Vault": "CAPX Vault",
  "CAPX places the trade onchain and records your holding.": "CAPX hufanya biashara kwenye mnyororo na kurekodi umiliki wako.",
  "CAPX will not route this trade. Use issuer mint and redeem instead.": "CAPX haitapitisha biashara hii. Tumia kutengeneza na kukomboa kwa mtoaji badala yake.",
  "Cost basis": "Gharama ya ununuzi",
  "Could not rebuild your cost basis": "Imeshindwa kuhesabu upya gharama yako ya ununuzi",
  "Custodial trading is not enabled on this deployment yet.": "Biashara ya udhamini bado haijawashwa kwenye mfumo huu.",
  "Disconnect": "Tenganisha",
  "Discover CAPX Equities": "Gundua CAPX Equities",
  "Enter an amount": "Weka kiasi",
  "Every claim on this page resolves to an onchain address you can check yourself.": "Kila dai kwenye ukurasa huu linaishia kwenye anwani ya mnyororo unayoweza kuthibitisha mwenyewe.",
  "Every share, accounted for.": "Kila hisa, imehesabiwa.",
  "Everything, marked to the chain.": "Kila kitu, kimepimwa kwa mnyororo.",
  "Export CSV": "Pakua CSV",
  "Feed status": "Hali ya feed",
  "Fund with mobile money": "Weka pesa kwa simu",
  "Fund with shillings": "Weka pesa kwa shilingi",
  "Held by customers": "Zinazoshikiliwa na wateja",
  "How a deposit works": "Jinsi amana inavyofanya kazi",
  "Institutional grade": "Kiwango cha kitaasisi",
  "Latest round": "Raundi ya mwisho",
  "Live board": "Ubao wa moja kwa moja",
  "Live feeds": "Feeds za moja kwa moja",
  "Locked in custody": "Zilizofungwa kwenye dhamana",
  "Market value": "Thamani ya soko",
  "Mint only": "Kutengeneza tu",
  "More than you hold": "Zaidi ya ulizonazo",
  "Multiplier": "Multiplier",
  "No B20 positions yet": "Bado huna hisa za B20",
  "No price history available from the exchange right now.": "Hakuna historia ya bei kutoka sokoni kwa sasa.",
  "No secondary market yet": "Bado hakuna soko la pili",
  "No securities have been issued yet.": "Bado hakuna hisa zilizotolewa.",
  "Not available to US persons": "Haipatikani kwa watu wa Marekani",
  "Nothing yet. Deposits and trades show up here.": "Bado hakuna kitu. Amana na biashara zitaonekana hapa.",
  "Onchain references": "Marejeo ya mnyororo",
  "Onchain supply": "Ugavi kwenye mnyororo",
  "Open portfolio": "Fungua uwekezaji",
  "Oracle rounds read": "Raundi za oracle zilizosomwa",
  "Order ticket": "Fomu ya agizo",
  "Read your positions off Base.": "Soma hisa zako moja kwa moja kutoka Base.",
  "Scroll to explore": "Sogeza chini kuona zaidi",
  "Search ticker, company or sector": "Tafuta alama, kampuni au sekta",
  "Session P&L": "Faida ya kipindi hiki",
  "Shares held": "Hisa ulizonazo",
  "Sign in first.": "Ingia kwanza.",
  "Sign in to CAPX": "Ingia CAPX",
  "Signed in": "Umeingia",
  "Snapshot": "Picha ya sasa",
  "Switch to Base to trade": "Badilisha kwenda Base ili kufanya biashara",
  "They convert automatically.": "Hubadilishwa kiotomatiki.",
  "Token decimals": "Desimali za tokeni",
  "Tokenized equities are not available to US persons. Nothing here is investment advice.": "Hisa za kidijitali hazipatikani kwa watu wa Marekani. Hakuna chochote hapa ni ushauri wa uwekezaji.",
  "Tokens outstanding": "Tokeni zilizopo",
  "Top movers": "Zilizopanda zaidi",
  "Transparency": "Uwazi",
  "USDC, ready to deploy.": "USDC, tayari kuwekeza.",
  "Underlying shares": "Hisa halisi",
  "Unrealised": "Ambazo hazijauzwa",
  "Usually within a minute, ready to invest.": "Kwa kawaida ndani ya dakika moja, tayari kuwekeza.",
  "Welcome to CAPX": "Karibu CAPX",
  "What that means": "Maana yake",
  "What you actually paid.": "Ulicholipa hasa.",
  "You buy shares.": "Unanunua hisa.",
  "You receive (est.)": "Utapokea (makadirio)",
  "Your details live behind your account.": "Taarifa zako ziko nyuma ya akaunti yako.",
  "Your name": "Jina lako",
  "Your onchain book.": "Mali zako kwenye mnyororo.",
  // A registered company name. Listed so the coverage check stays honest about
  // what is deliberately untranslated rather than what was forgotten.
  "CRDB Bank Plc": "CRDB Bank Plc",
  "Tanzania’s largest bank by assets, listed on the Dar es Salaam Stock Exchange. One CRDBt is one share, held in custody and settled in shillings.":
    "Benki kubwa kuliko zote Tanzania kwa mali, iliyoorodheshwa kwenye Soko la Hisa la Dar es Salaam. CRDBt moja ni hisa moja, inashikiliwa kwa dhamana na hulipwa kwa shilingi.",
  // Landing reorder, CRDB quick buy and bank-transfer deposits.
  "Tanzanian shares in shillings, settled the same day. US shares from the same account.": "Hisa za Tanzania kwa shilingi, zinalipwa siku hiyo hiyo. Hisa za Marekani kutoka akaunti hiyo hiyo.",
  "1 year": "Mwaka 1",
  "And beyond the DSE": "Na zaidi ya DSE",
  "Browse US equities": "Tazama hisa za Marekani",
  "Buy CRDB in shillings": "Nunua CRDB kwa shilingi",
  "Buy a fraction of a DSE-listed company from mobile money. No broker visit, no minimum lot, no waiting three days to settle.": "Nunua sehemu ya kampuni iliyoorodheshwa DSE kupitia pesa ya simu. Hakuna kwenda kwa dalali, hakuna kiwango cha chini cha hisa, hakuna kusubiri siku tatu kukamilika.",
  "Fee": "Ada",
  "From": "Kuanzia",
  "Live on CAPX · one CRDBt is one share in custody": "Inapatikana CAPX · CRDBt moja ni hisa moja iliyo kwenye dhamana",
  "Open an account, fund it from mobile money or your bank, and own a Tanzanian share the same day.": "Fungua akaunti, iweke pesa kutoka simu au benki yako, na umiliki hisa ya Tanzania siku hiyo hiyo.",
  "Settlement": "Ukamilishaji",
  "Tanzanian shares,": "Hisa za Tanzania,",
  "The same shillings buy US equities too, priced by Chainlink and settled onchain.": "Shilingi hizo hizo zinanunua pia hisa za Marekani, bei kutoka Chainlink na kukamilishwa onchain.",
  "The world's companies,": "Kampuni za dunia,",
  "US equities": "Hisa za Marekani",
  "Your shillings,": "Shilingi zako,",
  "at work on the DSE.": "zikifanya kazi DSE.",
  "from the same account.": "kutoka akaunti hiyo hiyo.",
  "in shillings, same day.": "kwa shilingi, siku hiyo hiyo.",
  "today": "leo",
  "fee": "ada",
  "settles same day in nTZS": "inakamilika siku hiyo hiyo kwa nTZS",
  "Account name": "Jina la akaunti",
  "Account number": "Namba ya akaunti",
  "Amount, exactly": "Kiasi, kamili",
  "Bank to select": "Benki ya kuchagua",
  "Copied": "Imenakiliwa",
  "Copy": "Nakili",
  "Get bank details for": "Pata maelezo ya benki kwa",
  "I have sent it": "Nimeshatuma",
  "Preparing…": "Inaandaliwa…",
  "Reference · put this in the description": "Kumbukumbu · iweke kwenye maelezo",
  "Send a bank transfer": "Tuma kwa benki",
  "Send from any Tanzanian bank. A different amount or a missing reference cannot be matched automatically.": "Tuma kutoka benki yoyote ya Tanzania. Kiasi tofauti au kukosa kumbukumbu hakuwezi kulinganishwa moja kwa moja.",
  "Sending prompt…": "Inatuma ombi…",
  "Valid until": "Inatumika hadi",
  "Waiting for payment": "Inasubiri malipo",
  "You will get an account and a reference to pay from your own bank app. Any Tanzanian bank works; it usually lands within about 10 minutes.": "Utapata akaunti na kumbukumbu ya kulipa kupitia programu ya benki yako. Benki yoyote ya Tanzania inafaa; kwa kawaida hufika ndani ya dakika 10 hivi.",
  "Minimum lot": "Kiwango cha chini",
  "None": "Hakuna",
  "from the DSE to Wall Street.": "kutoka DSE hadi Wall Street.",
  "One account, funded from mobile money or your bank. Own CRDB on the Dar es Salaam Stock Exchange the same day, and US names like NVIDIA and Apple alongside it.": "Akaunti moja, inayowekewa pesa kwa simu au benki yako. Miliki CRDB kwenye Soko la Hisa la Dar es Salaam siku hiyo hiyo, pamoja na kampuni za Marekani kama NVIDIA na Apple.",
  "DSE": "DSE",
  "in shillings": "kwa shilingi",
  "US stocks": "Hisa za Marekani",
  "names": "kampuni",
  "in dollars": "kwa dola",
  "Browse US stocks": "Tazama hisa za Marekani",
  "Send from the account you enter above. You will get an account and a reference to pay from your bank app; it usually lands within about 10 minutes.": "Tuma kutoka akaunti uliyoandika hapo juu. Utapata akaunti na kumbukumbu ya kulipa kupitia programu ya benki yako; kwa kawaida hufika ndani ya dakika 10 hivi.",
  "Send to a bank account": "Tuma kwenye akaunti ya benki",
  "Choose your bank": "Chagua benki yako",
  "Mobile money": "Pesa ya simu",
  "Bank": "Benki",
  "Listed on the Dar es Salaam Stock Exchange. One {sym}t is one share, held in custody and settled in shillings.": "Imeorodheshwa kwenye Soko la Hisa la Dar es Salaam. {sym}t moja ni hisa moja, inashikiliwa kwa dhamana na hulipwa kwa shilingi.",
  "suspended": "imesimamishwa",
};
